# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PaddleStationApp' do

    pod 'Stripe'
    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaddleStationApp

  target 'PaddleStationAppTests' do

    pod 'Stripe'


    inherit! :search_paths
    # Pods for testing
  end

end
